#!/bin/bash

set -x

#Expose argocd-server
#By default argocd-server is not publicaly exposed. 
#A Load Balancer is used:

kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

#Wait about 2 minutes for the LoadBalancer creation

export ARGOCD_SERVER=`kubectl get svc argocd-server -n argocd -o json | jq --raw-output '.status.loadBalancer.ingress[0].hostname'`

#Login
#The initial password is autogenerated with the pod name of the ArgoCD API server:

export ARGO_PWD=`kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d`

#Using admin as login and the autogenerated password:

argocd login $ARGOCD_SERVER --username admin --password $ARGO_PWD --insecure
